[dev]
    command = 'bun run start:quiet'
    publish = '_site'
    functions = '.netlify/functions'

[functions]
  directory = "src/functions"

[[plugins]]
  package = "netlify-plugin-cache"

[plugins.inputs]
    paths = [
      "_site/img/",
      ".cache"
    ]

# Brid.gy Fed set up to use henry.codes as a fed target
[[redirects]]
    from = "/.well-known/host-meta*"
    to = "https://fed.brid.gy/.well-known/host-meta:splat"
    status = 302
[[redirects]]
    from = "/.well-known/webfinger*"
    to = "https://fed.brid.gy/.well-known/webfinger"
    status = 302
