export default [
  {
    date: '2021-08-18T14:22:39.132Z',
    publisher: 'Awwwards',
    title: 'Portfolio FW19',
    link: 'https://www.awwwards.com/sites/creative-developer-portfolio',
    award: 'Honorable Mention',
  },
  {
    date: '2021-08-18T14:22:39.130Z',
    publisher: 'Awwwards',
    title: 'Portfolio FW19',
    link: 'https://www.awwwards.com/sites/creative-developer-portfolio',
    award: 'Mobile Excellence',
  },
  {
    date: '2021-08-18T14:24:59.839Z',
    publisher: 'CSS Design Awards',
    title: 'Portfolio FW19',
    link: 'https://www.cssdesignawards.com/sites/creative-developer-portfolio/35579',
    award: 'Special Kudos',
  },
  {
    date: '2021-08-18T14:24:59.838Z',
    publisher: 'Humans',
    title: 'Portfolio FW19',
    link: 'https://humans.fyi/u/henry.codes',
    award: 'Site of the Day',
  },
  {
    date: '2021-08-18T14:22:39.137Z',
    publisher: 'Awwwards',
    title: 'JD Minnick Portfolio',
    link: 'https://www.awwwards.com/sites/jr-web-developer-portfolio',
    award: 'Honorable Mention',
  },
  {
    date: '2021-09-16T17:46:28.350Z',
    publisher: 'Awwwards',
    title: 'Faculty',
    link: 'https://www.awwwards.com/sites/faculty-2020',
    award: 'Honorable Mention',
  },
  {
    date: '2021-09-16T17:45:12.430Z',
    publisher: 'Awwwards',
    title: 'Portfolio FW21',
    link: 'https://www.awwwards.com/sites/soon-creative-dev-portfolio',
    award: 'Honorable Mention',
  },
  {
    date: '2021-09-16T17:45:31.479Z',
    publisher: 'Awwwards',
    title: 'Portfolio FW21',
    link: 'https://www.awwwards.com/sites/soon-creative-dev-portfolio',
    award: 'Mobile Excellence',
  },
  {
    date: '2022-11-30T19:41:54.400Z',
    publisher: 'Awwwards',
    title: 'OddCommon',
    link: 'https://www.awwwards.com/sites/oddcommon',
    award: 'Honorable Mention',
  },
  {
    date: '2022-11-30T19:43:58.937Z',
    publisher: 'The FWA',
    title: 'Borderless VR',
    link: 'https://thefwa.com/cases/borderless-vr-p2',
    award: 'FWA of the Day',
  },
  {
    date: '2023-01-27T01:41:00.148Z',
    publisher: 'Awwwards',
    title: 'Borderless VR',
    link: 'https://www.awwwards.com/sites/borderless-vr',
    award: 'Site of the Day',
  },
];
